# Generated by Django 5.2.8 on 2025-12-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.TextField()),
                ('imagem', models.ImageField(upload_to='receitas_fotos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
